### ISSUE TITLE
sorry bout that 

### ISSUE THREAD

**Issue by Fouws** [united-meows/Seriex#1]
Sorry 'bout that
Sorry 'bout that

A-T-E, she eat me up (Sorry 'bout that)
ATV what she ridin' on
Bend the bitch over in Calabasas (Yeah)
![image](https://user-images.githubusercontent.com/67429196/169349707-0b1709e3-401b-4cd0-aa67-beb422ffe477.png)
kafa atilir

**Comment by ghost2173** [comment]
Merhabalar Fouws, sorununuz anlaşılmamıştır. Lütfen daha açıklayıcı şekilde anlatır mısınız?

**Comment by Fouws** [comment]
Merhabalar ghost2173, sorununuz anlaşılmamıştır. Lütfen daha açıklayıcı şekilde anlatır mısınız?

**Comment by ghost2173** [comment]
Atatürke kafa atma isteğiniz anlaşılmamıştır.

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169351853-c6adfa2f-4b0e-4c7b-95af-c1fe8175597f.png)
Sorry bout that

**Comment by ghost2173** [comment]
Sorun anlaşılmıştır.
Konu kapatılmaktadır, iyi forumlar.

**Comment by Fouws** [comment]
`
![image](https://user-images.githubusercontent.com/67429196/169351982-471bc3db-8ec9-4852-b24f-1f4fc4f0ebda.png)
`

**Comment by ghost2173** [comment]
bana bak o allahini

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352015-caf817f3-35d2-46db-a548-95e2160b96dc.png)

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352099-6783346a-35af-44c4-a60c-cf0fd480e579.png)
dur sallaniyom

**Comment by ghost2173** [comment]
![insanlarınyuzde99unungöremediadam](https://user-images.githubusercontent.com/69243988/169352182-ca80d2e3-e875-4235-857c-dbf859efaa87.png)
tamam

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352195-2ea2f958-a71e-46a1-9b5b-19c1c1527609.png)
kitap yazarken ben

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352255-c58dcd7c-3122-47c6-9430-51877d55fb00.png)
kafa atan o kişi

**Comment by ghost2173** [comment]
![maymun1cn](https://user-images.githubusercontent.com/69243988/169352279-a88e0089-e992-4e9f-933c-081c5396f57f.png)

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352329-ec2bc3ab-66ef-46cb-9682-9e65594e7937.png)
gülen bıyık

**Comment by ghost2173** [comment]
Sorun iyice anlaşılmıştır iyi forumlar.

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169352388-bc5a53ef-ee52-46ba-9fee-33a361c44175.png)
anlamadın mı?

**Comment by ghost2173** [comment]
yok
anladım.

**Comment by ghost2173** [comment]
Neyse konu kitlenmiştir iyi forumlar.
