### ISSUE TITLE
turnuva

### ISSUE THREAD

**Issue by Fouws** [united-meows/Seriex#2]
![image](https://user-images.githubusercontent.com/67429196/169352627-365521e5-ff2e-4a71-9dc6-1259f29480b0.png)
katılalk mı

**Comment by ghost2173** [comment]
yok

**Comment by Fouws** [comment]
ne demek yok

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353075-53746a8b-9052-4cc5-af6c-cb6835f299c8.png)

**Comment by ghost2173** [comment]
@slowcheet4h

**Comment by ghost2173** [comment]
sen katilsana

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353161-dcda7b3c-7783-4da1-b834-1eeda653edc0.png)
1000 kisiye sorry bout that mi

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353279-675789b0-04df-4512-aa31-b65b4ae19166.png)
saygıyla kafa koyulur

**Comment by ghost2173** [comment]
lan noluyo

**Comment by Fouws** [comment]
beşiktaşlılar beğendi bile

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353497-db7ae544-7900-415d-9813-1f00eb6bec7b.png)
![image](https://user-images.githubusercontent.com/67429196/169353606-e7fdceba-7a69-48a1-809d-4ff0860ac753.png)
![image](https://user-images.githubusercontent.com/67429196/169353567-74c052e5-8297-44c2-9465-cdc7fcc3d178.png)
![image](https://user-images.githubusercontent.com/67429196/169353587-1236a7a9-4d22-406e-ac2a-88fc57befc2e.png)

**Comment by theviserys** [comment]
ananizi

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353724-a6cdeab3-4961-4596-9176-76171e096b1d.png)

**Comment by Fouws** [comment]
@ViserysTR

**Comment by Fouws** [comment]
bu adam kim

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353887-cf81a384-fabd-459a-8dac-651f98df85ac.png)
şapkamı takarım gelen kafaları engellerim lmao!!!!

**Comment by ghost2173** [comment]
lan bi bok yapin seriexe alo

**Comment by Fouws** [comment]
public void ataturk() {

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169353984-f220b878-fd46-4703-bcce-4f7a3f0d2326.png)
atam kodları kulağıma söyler yazarım

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169354187-07b2dbad-85e2-4db7-bd05-ba917b29485d.png)

**Comment by ghost2173** [comment]
atam vatatatan

**Comment by Fouws** [comment]
ak/party ghost2173 mu###

**Comment by ghost2173** [comment]
yok

**Comment by Fouws** [comment]
ataturk dogdugu zaman bunları okuyup boyle olcak (bence) yanı sımdı herkesınfikrini sikemyim lmao!!!!data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYVFRgWFhYYGBgaGhweGhwaGhwYGhwaHhgaGhoaGhocIS4lHB4rIRoYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISGjQrISE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NP/AABEIASYArAMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAEAQIDBQYHAP/EAD0QAAIBAgQEBAQEAwcEAwAAAAECAAMRBBIhMQVBUWEGInGRE4GhsTJCwdEHFFJicpKi4fDxFTNTcyMkVP/EABgBAQEBAQEAAAAAAAAAAAAAAAABAgME/8QAIBEBAQEBAAICAgMAAAAAAAAAAAECESExAxJBURMiYf/aAAwDAQACEQMRAD8ApkMSqtxpIlaT5oQIqW33jwpEkciMLwCUr2W0HZLmNdjEzGIHimQYdhFNnv8A03gYOkN4ebkjqplgKdfKn937SvrLrDqzkUqJ/vj6iV9SrreFR4g2g9o7EVM24jVMIUDvPGOUTzJILzBtdB/6yPrKqqL6Sy4efIvdWEr6m5mlRinzvrJqa6yJNYRRggthow/sgwAoZYtzI/ot7GBXgRu0npOLQdlvHAQBSkcxjTcR6kTCGjWedLSawtGMlxAFcE7GMYGOamb6T1jvNDyuZZcHe7gHmCPpK7UwzhTgVUFjv+kCxxP/AGV7VGH0v+kpncky3rG9Nu1Q/aVKq2a/KCoS+trQhEuJIKQkyAdIOBfhyTLcR7+kVFjgN4d+Qf3h9LwPLe8scAo8h/tH7SBEFyO5lUEgktOJVTKbT1JrQLLDjQ+jD6QAJflDsI21+v3BkJPygButjEzGGVEBW9tRBbdoAOJRmHlBjaYawuD3l8tLDgaYoWkfw8Nv/M/QzIqwT0PsYjE8lPsZas+G/wD0n2kb18MN8Q59FNvtBxVGow/I3sZGKjH8pHyMtTisKdPj1P8AAf2iK+G/81X1yH9pRXDN3kuDzZ1ve1xLBnw1v+5V/wAB/aeTEYcEWesSOXw21+kApkslUDk4+sq7npLTDVM61mCPY5TYqQSb8rzyIgXMEZT0c6+0CtKOdlMlTCP/AEGFnEX3IHYSWliT1g4q3UjcEesQVLS0rsDdidLbchKjidAgKyC621t1lFpgn8oNiVDXJGtr9ZBrnNup+8tPD2FcUGFgA4O+/aWWA8OVGsXCKOtySflJPLVnFGaQO8ErUddBNvV8OWXyMpP9oH7jaZ3E0jTYo5pKw5EMfnvHGQeGBG46H2Ii1afmIHWEPUTIbugHVVP7xXxKKbXPLZL8uplFdUVhIfhN3ljUxqblnHyT9oz+eTrU9x+0Bg4th90ww9THDilFtThl+kBwdEOhOQXuLalvUy1w/BEYfjA7ZL/UkSAduIIXyDD07gXubW2vvIDxmx0w6fSLVwipiUp5gwbe4A5Hv2l2cPRUgFEPp/xIvVGePtyw9P2EhxXid0sMlNb/ANkH7y9VqAJApiYzxg6l0ZRl0IIv3msztS0VT8T1iwswB/uL+0savGMSrCzo4IBuKYHqD0ImK4UjPWRARdjYexm6/wCjugGcqRqCLm5FuUuvrCS1Bh+OVitT4r7L5NLWa+m0r8ZxJ9La3hOPVFzIugK5QO+lpd4Hw5TFHLUIDEXzbZfnM28azm1kBWqFr6AQyni29Zbt4ZNjaorJrb+qVFLhVRHKEFteQ5TP2i/Wj6bFgB1hGCW5ykc9ZJVwmVLqhB05HSOw9Mg5mGWJqVLmxfYLFgFUsem2naXtPEETBcOrO2IG5XMOZsLX5TbT0/DmcrGtVYU8V1Hzmc8ZYZCab28xuCe3KXiroIB4hKGkBu1xbtM6zPwRljhEtbtHql7Gw2/SOqIbj0g6OSB6/rOSkocOV6xZzddMo295dfy6f+NPb/SZziHERQdObG97dBLOnx+iRfOR2mb11z9eMlww1Cjqma5ICgbkljtLbBcJxKamk5M0HhLhBphqj6s58vYdZpy52ltZzi1z6nwWs7/FcZAmwYanQg/eB1OMqpsQSe06LjMOKiMjE6i176znGO4Sabsrcjoeo5GSXtXWeRG3GlvcI30lNx/GLVy2UjqZNXK5stwe4nqmFQrrOuc/lytUdGo1J0cflIYHrabar4vSqnlTKyi5vsfSYwuEbK3mS/rFw1i5OljyGg1l1mUmrPEWnC8Wa2IUub3cadrzpGPqWuGW68xa9xOefDC07oACNbjeFJ4zrhMpCNYbkazG8d9N41z212AqLm8ikIdNRlt7wvE1slu85rX43VrG7Pp0BsBDeH8cdNG86HQhjfTtOf8AFZG58s66DgKhzXYhhtrb3j/EIVUvYAnTpKjhfEcKVGVlS24JsR6XnuJYpcVXp06ZJRT5iNBbn9Ixi28a3qfXwj4VhHd1KDKAdSeU3NHD/OCIgUWA0h+Be+naey5uc+Hm72pTTUAkn5zI8e4grkBDoNz1mzdAwIIuCLGY3jfAjSGdCSnMHUr/AKThbeNK3EZrizEabaQLGYgU0uTbU9zePxtRhb0mNx+NZ6rAm4Gg6SSdpTcTind851ttc8ukHqksb5RrCFSF08E5FwjW9J15EdjtbQbSI1hfKbqT10+szHFPEppoTf66/SQ8O8WiuoV1sTsR1E83t6ftJ4aoVimj/Ijn6zGeNuIDOqaXN7Eb5ZcV8ULXDcvac347xDPVZwSQDZT6RjzrjPyX+ptQZdRa0FfFXNrm0DrY5mGUj5x+G4dVc3CkA8zoJ6Y8w4ZGtexi4OiC+UCw68pJhuEKpGd7nou31l5QwiaE3PoYaW6YSkMMcwUeU+Y6TmTPrYbTTeJOJXT4anTaZNjESpVuOcIpvfeDIDaSLcQiwpvOgeAKa5XY/iuAPQC8weCp+Us2t9FH6za+G64pW78pc3l6N1m6D9ZNQqG8rcLjQ+awN1/2IdgCSRcev7zrrlz0WkZiEDIwOoKm/tJY2psfQ/aeVtzPi/lQ25XtOcNUIcnvOmcV1V/RrfWcvxBIJMuU00OC4iij8ALdTHPxVyb5yOw2mfwzwoMZuQBV8U7/AImJllwWoVdd95VqIdhzYgg2tHINZWx6AZWNidNZn34Ju5e4JJAlmmID08rgH7+8rK1Yp5QSRykmeJaiUImgUX9JN/OnLYSqqVdd40VJUXOEcs14ViXYLoTeVWDxWS9pM2KLbw0r8aCYK4HSFYmpEXKV1teGQQe0kV77RHUbAREsp13gXWBUAC5lxhMWxcADS+8r+G4pQqc0YZXFtc40YexBHpC6xyOUXUg2hpueFYnU5eduf0mn4UttD0/Wc2wtRlsbmbDg3GgLB9dNDLPGfqXzetXIqz2HqDIVxoIvaRh2O8zM38nWVroDmAW5NxOX8awZpVGQ8jceh1nWMdRIcgCZ3xLwX4qApbOt+drjpecs65rjprPcyudJpFzT2IQo7I4IZTYg9ZD8SdnE+mddY98RbaClp5H1HS+sCyw+JJG+shrV777xiVwjXA06SPEPmJYQI2fWJntGZozeAbSfSKXInqdMhb8p7MBrAbUcETyLcbyKrUv2kakwDaaGxtvLHCcEQjM769BKWk5XeHpXZtrwLVFSiDkYm9tNDqNAR0lhgU1zN+I6yswWFN8z78hLylvDSYx+ExWUkRogmJcKd9W0tA2PCuMKxCE6nlNROO4asaOIpsSSCfadaSvmsRsf1mp3Xj9AHG0mzk9doMKGuolnVOUa7n5wU1/T2E4azzVbmvHHGfFpJxla4t57fIAWlPabf+JPDcrriBtU8rDowHL5TEX7zrL4c62mJ4DTdh+X05yGp4SXNZHt6zR0sNbcyWoLazh9v9dLn/GOreEqgGjqbfL2glXw7WUaLm9DNyj5iCBoDCARe19ZP5LFmJXKsTwusn4kb1tpBSjLoQR6i07FicMyjkT2mX8YYQ/CR8uzam3WdM76zrP1Y6jiWXlIarFjfbsJPQwhcnkJc4bCImwv33nRzUVKmG36Q/h+FBBMkxuGUXYaQzDi1PLprABThxdr8ry4oYVU2Egw9YKtucRsVDSxR7dJOj9DKX48lp4rrAtqlaynMSO43+UqcKTmJJJ6E77wTGYrMQok9EmwgE8aS6I4P4XBnSfDXEKdSki5xnA1UnX1nOwgek6HmNOxlLVxJBGtiABcaSy8HcsZTKgXv7QA09ZhvBvGqlSr8J3ZlKkgMxNiOl5vsuk56tt8rGc8a8K+PhjY+an5x3sNR7Tklp3it5gVI0II+RE5B4i4I2GrGmvmWwYEjWxJ/aXNSuhWkYpNzBI+0emLUG1rHY3/AHkYqB72bY6gTxzXHpslSrRXZiyDsIw0wrAKRY8zcn3kVV3HpffWPo12bW3br94+37OeUtZyPw+Y+0oPFrn4PnaxJFlEvyotYgdRe8x/jF2LorC1hfQ3vfn2nT45bWfk9KWibCG020gSbCPeqAs9TgZj61yFEt8Jg86DMT8pn8N5nJP/ADNRhqllFoZRLwlB+ZvcRw4UnVoUKoimoIaCDhaX1LW+sjxPDVAOV+XOS1sTYwDF4glSAdYANBQram8KSsSbCB08AxHmNoXh8KE5knrDKzwqkXuLfOZmv+IgX3mnoEBSx5C5mYq7+8DU/wAPqf8A9gv/AEofrOlitOffw8TzVD2E3N5jXtqJneD4nhFOqQzb2t9/3khtJEqaSKztKmPzgHuN/aLTA1t119YQ7Ane3yiEbG955eT9PVzhd1sLfOO/k3Gy79I04IubW09oXQwOUWZmIGwudJvOe+2Na/QMofzAjvpObcYrmrVdxcqDYegM6Tx+sKdByOSm3qRpOZ0Dpr/vrO+MyOOtXQYNI6zwuvQ5j2gNNczgGdHMRhaZUZpcUq+g1ldVNlAHKKj6Q0s3ryNq0EFS8a7QJXqwEOzPpErVLQnhShg3UfaGR0QGRMTfQySmbw0lDnIwHSBUETL5rE9oY6EK1xylOlew0UfWSjfeCSpVwo0FhNMw1ma8Ar/8Tt1f7ATSmZvseZvWMzzxaA18ZlNsl+8lBBwgB1JiIqrtHu5MYjWIJFxMcjfbR/DHu/yi8TUq1xsYRhKSMwdNLAgiTY6jnQ9RqJnvl1+v9eOd+N8WRTVP6zr8pkMPtNh4n4ZWruiJTZgOYHMnmTHYT+HmIsC7oinfXMw9p1zqRxuKyNd/KYNh8KSpfmDOvUf4c4bKMzuW6gr9rTO8V8OJQqFCxYflt9JualY4wjm415RmebJODIr6gNfa/XvJMTwRG/Ivy0l6cYtKs9UfpNTX8PoWAAKnsd4bV4OioBYac/1jqueupvaxvLHB8PqGxW1+l9ZdY/hwXzjlAMcMjK6OT/Vyhk3GYFwdB6gawZ/iUiMykeoM2DqtektRdGFvpKfidYs3m1uB9oaR4fFh0PUA3EoQbSyemEuy6dvWQYLCmo6ooJJP+zDLofgunbDA9SZdvvE4XgglNUGmUWhBTWc++W+BWSJlli9PSC/DkghZJGUln8NSCQNeUHWmR1gD4asyG4lknFEtqCD7wf4APLfvPNhBbaZuW86sFf8AUEI8t799JCcW99/oJgeOeJHo12RACF0+fOQp44Ybob+sz9dOk+TLpSY4fmHzEw3iHjavXOU6LoPlK2t41ZlICEEi17zMfHJa5O5nTGbL2uW9y+I1mHxYzAlrC4+Qlu/EqQFy4mG+PpERyTOrDVVOMUywYZtO0XEcZRhYA/OZwMAI0VI4LDFYssCvaVKWLZT0hDtAKpOcEdoGl4IjUwR3uvTbWDcaYMwIFv35wVcS3WTanzMYFTi3INpu/BHCVSn8VrZm27CYTEkF78r2PpOx8NwqpSQLsFFvaTXpImRwI01ekjYdIgpmYa6meqZHf1iZTzkZeBP8Nk3MsOGUbm5Oh5fKMNEsfNJgCp8pHoZlRFfKv4UU9dJBSpjQlQNeUe5J2sO8irjKj9lY/QxVjhXGqxfEVGOt3b7kfpKstdrQhzdmPUk/WCI3n9Tb3nWTw50UG0ns09UplSVYWINiJG+0qJVqSVa46yu1jssCyOJB5yL+Y6QLLJQkA5a94b8BStwbmVlJZYYZT0gew9jDWokKTYgd5Hw9FBN5YPdxkG50HSGlBgyvxELajML89L9J2ihikZAVYW5DblMRwTwcqnNWdWPQHSbDB8MC/gbQcjtOd0sgjytqCD6GeydJFiayI2XylugtIndelvQkSCd6Z6H2kHwG6T3x3Gocgd9Yv88/9f8AlEouonwweQni46xlWoT+YD6zDYinQJGgtBcS97ryIIPoR/rEpMdi/sJ7DMA3MnqRpNWxlwXiOHNOq6HTKzC3zjPD2D+LiUX8oYFvQG81/wDEvhBSutRBf42lh/WP3lt4E8MtRQvWWztqAd1XlNy+GOeWE8WMDja+X8OcAf4VlS7S78TrbF1v/Z+ggNfDaAiaiBEW8mWmTyjEFjLOkwIvABGFMnTC23MJaMMCajRQd4WtUW0EBpyVTpDSNGOeWuAUs1hf5bynp6vNx4UwlgXI30Hpzk0NKporSsiZ3KD8d75rczy1g+BBCWqIrN1Duq/4ZOEjkS/MTnyL2oa1IMwbKq2GgUW/5nmykbQipTtBzEKYxEhKnrJis9aOC6qOmp19I0OhGha/S0Zh0zSMU7Nzv9JFG00HQ37zzVSDotwN4OzsdtTGfzTAWteF6bjcIKwXOt8rBl7EG+ntCWQga2EjSuxF9vSPuW3OneEca8XJbGVu7A/5RAalTQDnaaX+JFJRiEdT+JLH1U2mNLeadc+mKe6SWg2khMdRaVBqtHWvIFMmBho5Vj82kaGEIwFIu4XYEgfWBJwXh71XAANubW0AnSsLhgihQNBJsLg0RFAAFgNhaTrVVTtec7erIhZCBGBBDK1cMNoMKN9SZDjyvbfaIyqb/SMrGxtvHLAiKax+nQyR053kPxRHQdSr2Glr941MQzMcye0YmXpIhXIY6mRU7vl5m8VNBc84FXq3bWSMSbW2gWVNktYj/fynmqINrX73/WVyuwO0cUdtdBIvGS/idTDJSf8AMpK6dDrOcMNZ1Lxph82GZjupBHz0M5iBrOmfTGjcxEVHhi4YtsJ48OYannNso0a4jw0lw2ALMF6mw9ZecQ8N/ATOxBv069I7O8XikoIWl7wHDZqyKOtz8pR4A3Zug0mr8JpesT0ElI3DLYSEm8IdgRvIZzaNS8X4l4sRk0vpARrT1NLyWnRJjnrBOUAZwRpaDODeWIxIbVhGnIddYA3xRsYO+IyN5Rcd9Y9rHXaIpUC2/eRUdapmN9pPh3CrvBShipT1gFpiBD6T3F95VtSC7xlE2JOYgesHTPFVMvQdNNVNvlrORrOz0sr3B1v+05LxrC/Cr1E5Bjb0JuJvLOkaORCaVQ84Ih0klNpsWmHrlCrLoym4PfrLHjXiOtXp/DfKV0N7ea47yoEbUewjgFwwyt6zaeEafmZusxqjUTdeF1IQya9JGkItG/EgrVWGkVa/Xec2hdxaRIST2kKMXMJRcogGU8UFG0gxOKB1tBDVteJmDaQHfzAMnSstthIqeGNtoOcO/SFKHAB0iKc3aenpA9qR013jKVO7WvEnoFhUwgI35QQ4La5Fok9ALpUAl7TkniU3xNX+9PT01n2mlcjWk6naenp0YFCpG7menoaPUWM3nh8WQGJPTOiLQm5jXtewEWemFSU6ZA0MgquTa89PQPZbSXDqLz09IDg+0R3N56ekrc9P/9k=

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169354526-2189ac0e-29bb-4385-b9c9-d9250de1ce11.png)

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169354739-1b5bb745-cce5-4808-8ac9-7ec12ff186e8.png)

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169354783-df44655f-e3fa-485c-9c72-e2f3e5359979.png)
seriex in pluginini kurduktan sonra $patlat komudunu ghost yazinca ben

**Comment by ghost2173** [comment]
puhahaha

**Comment by Fouws** [comment]
![image](https://user-images.githubusercontent.com/67429196/169355078-668a3ea6-3619-41e1-a2b2-524bb7b61396.png)

**Comment by Fouws** [comment]
https://cdn.discordapp.com/attachments/942536324563496980/964884849590685827/20220416_164327_1.mp4?size=4096
