### ISSUE TITLE
C17

### ISSUE THREAD

**Issue by Emekkk** [united-meows/Seriex#3]
C17Packet yok

**Comment by slowcheet4h** [comment]
![image](https://user-images.githubusercontent.com/47327665/171377077-223de278-4180-4d58-9206-06f14a9014d6.png)
:skull:

**Comment by Fouws** [comment]
sorununuzu daha açıklayıcı bir şekilde paylaşır mısınız?

**Comment by ghost2173** [comment]
Sorun açıklanmadığı için kapatılmıştır, teşekkürler @Fouws.

**Comment by Fouws** [comment]
custom payload packet'e ihtiyaç duyulmadığı için eklenmemiştir iyi forumlar
