### ISSUE TITLE
discordbot.java kumalala kumalasevasta

### ISSUE THREAD

**Issue by Fouws** [united-meows/Seriex#5]
(bok fotografi)

**Comment by ghost2173** [comment]
lutfen sorununuzu aciklayiniz.

**Comment by Fouws** [comment]
iscordbot.java kumalala kumalasevasta

**Comment by ghost2173** [comment]
duzeltilmistir iyi forumlar

**Comment by Fouws** [comment]
Uploading abdulham-edit.mp4…

**Comment by Fouws** [comment]
https://user-images.githubusercontent.com/67429196/179829224-13db2b85-935d-4016-bdd5-5a028a8c77b3.mp4

**Comment by ghost2173** [comment]
yav duzelttik iste allahini s

**Comment by Fouws** [comment]
düzelttigimde hissetigim
![unknown_19 (1)](https://user-images.githubusercontent.com/67429196/179829299-eacad32a-c3b9-451e-9c26-0f08a4a87b74.png)

**Comment by Fouws** [comment]
aslinda olan
![unknown (17)](https://user-images.githubusercontent.com/67429196/179829385-b5ce9c06-903c-4162-8b97-b97c3d0a7b36.png)

**Comment by ghost2173** [comment]
allahini allahini allahini allahini

**Comment by Fouws** [comment]
![studyohakan](https://user-images.githubusercontent.com/67429196/179829421-eea1faad-214f-4caa-9225-6569feb683bc.png)
![qsadsad](https://user-images.githubusercontent.com/67429196/179829425-3a95e351-f129-4ec6-8bed-eb4dccba3266.png)
![Discord_kv5WakURqR-removebg-preview](https://user-images.githubusercontent.com/67429196/179829441-1e2d444a-24c1-4a70-b93f-f22c0447f521.png)

**Comment by Fouws** [comment]
ıssue sıl

**Comment by ghost2173** [comment]
kumalala kumalala kumala savesta

**Comment by Fouws** [comment]
1. ### __ss[sss](url)
